#!/bin/bash

# 1. takes in filename to format with astyle
# 2. creates tmp folder to output files
# 3. moves files in tmp folder to current folder
# 4. removes tmp folder

TMP="/tmp/astyle-fmt/"

OPT="--recursive --indent-col1-comments --delete-empty-lines --break-after-logical"

mkdir -p $TMP # create tmp file

for f in $@
do
	mkdir -p $TMP"$(dirname "$f")" # create dirs in tmp
	astyle $OPT < $f > $TMP$f # fmt files
	if [ $? == 0 ]
		then
			mv $TMP$f $f # overwrite local with fmt'd copy
		else
			echo "error: no files were altered."
			break # exits loop
	fi
done
rm -rf $TMP # remove tmp file