#! /usr/bin/env python

# this is written to shorten remove whitespace on comments,
# and remove trailing whitespace on things that comments follow

import codecs, sys

def comment(fl):
	for l in fl:
		line = ""
		for i, c in enumerate(l):
			# if line comment
			if i < len(l) - 1 and c == '/' and l[i+1] == '/':
				if l[:i].isspace():
					pline = l[:i]
				else:
					pline = l[:i].rstrip() + ' '
				line = pline + '// ' + l[i+2:].strip() + '\n'
		if len(line) == 0:
			line = l.rstrip() + '\n'
		sys.stdout.write(line)


# read from stdin
comment(sys.stdin)